### PR TITLE
adds CNAME file indicating domain

### PR DESCRIPTION
**Pull request by melbert**

### CODE REVIEW

**Comment by ninjapanzer** [comment]
branch deleted?

**Comment by melbert** [comment]
Yeah, having a fork with a `CNAME` file leads to it being taken because I'm not smart. Had to delete the branch.

**Comment by ninjapanzer** [comment]
oh heh

**Comment by ninjapanzer** [comment]
make sure you add the CNAME file to master so it will auto deploy to gh-pages on build

**Pull request closed without merging**
