### PR TITLE
adds middleman-blog, news layout, example post for news

### PR DESCRIPTION
**Pull request by melbert**
Adds Blog layout for News

Adds Pretty URLS :heart:

### CODE REVIEW

**Comment by ninjapanzer** [comment]
I love the pretty URLs :heart: 

One thing is the available section.
I just think it needs a styling tweak:
- Lets us a undecorated indented `<ul>`
- Lets just style the `<p>` so it is the same line height as the other items and indent it a bit (I tried this one in the browser)
  
  ```
  margin-top: 0.3em;
  margin-left: 1em;
  ```

**Comment by melbert** [comment]
tweaked the style :tada:

**Comment by ninjapanzer** [comment]
:wolf: 
:necktie:
:jeans:
:mans_shoe:  

Business Wolfman

**Comment by ninjapanzer** [comment]
I am going to pend deploying this until I can get a email formalized since the book url changed

**Pull request merged**
